config/routes.rb
Rails.application.routes.draw do
  resources :cables
  resources :fiber_strands
  resources :dev_ports
  resources :term_devs
  resources :net_racks
  resources :locations

  root 'welcome#index'

end

app/models/dev_port.rb
class DevPort < ActiveRecord::Base
end

app/controllers/dev_ports_controller.rb
class DevPortsController < ApplicationController
  before_action :set_dev_port, only: [:show, :edit, :update, :destroy]

  # GET /dev_ports
  # GET /dev_ports.json
  def index
    @dev_ports = DevPort.all
  end

  # GET /dev_ports/1
  # GET /dev_ports/1.json
  def show
  end

  # GET /dev_ports/new
  def new
    @dev_port = DevPort.new
  end

  # GET /dev_ports/1/edit
  def edit
  end

  # POST /dev_ports
  # POST /dev_ports.json
  def create
    @dev_port = DevPort.new(dev_port_params)

    respond_to do |format|
      if @dev_port.save
        format.html { redirect_to @dev_port, notice: 'Dev port was successfully created.' }
        format.json { render :show, status: :created, location: @dev_port }
      else
        format.html { render :new }
        format.json { render json: @dev_port.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dev_ports/1
  # PATCH/PUT /dev_ports/1.json
  def update
    respond_to do |format|
      if @dev_port.update(dev_port_params)
        format.html { redirect_to @dev_port, notice: 'Dev port was successfully updated.' }
        format.json { render :show, status: :ok, location: @dev_port }
      else
        format.html { render :edit }
        format.json { render json: @dev_port.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dev_ports/1
  # DELETE /dev_ports/1.json
  def destroy
    @dev_port.destroy
    respond_to do |format|
      format.html { redirect_to dev_ports_url, notice: 'Dev port was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dev_port
      @dev_port = DevPort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dev_port_params
      params.require(:dev_port).permit(:name, :portno, :type, :RackID, :odfid, :fiberid)
    end
end

app/helpers/dev_ports_helper.rb
module DevPortsHelper
end

app/views/dev_ports/_form.html.erb
<%= form_for(@dev_port) do |f| %>
  <% if @dev_port.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dev_port.errors.count, "error") %> prohibited this dev_port from being saved:</h2>

      <ul>
      <% @dev_port.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :portno %><br>
    <%= f.number_field :portno %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :RackID %><br>
    <%= f.number_field :RackID %>
  </div>
  <div class="field">
    <%= f.label :odfid %><br>
    <%= f.number_field :odfid %>
  </div>
  <div class="field">
    <%= f.label :fiberid %><br>
    <%= f.number_field :fiberid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dev_ports/edit.html.erb
<h1>Editing Dev Port</h1>

<%= render 'form' %>

<%= link_to 'Show', @dev_port %> |
<%= link_to 'Back', dev_ports_path %>

app/views/dev_ports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dev Ports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Portno</th>
      <th>Type</th>
      <th>Rackid</th>
      <th>Odfid</th>
      <th>Fiberid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dev_ports.each do |dev_port| %>
      <tr>
        <td><%= dev_port.name %></td>
        <td><%= dev_port.portno %></td>
        <td><%= dev_port.type %></td>
        <td><%= dev_port.RackID %></td>
        <td><%= dev_port.odfid %></td>
        <td><%= dev_port.fiberid %></td>
        <td><%= link_to 'Show', dev_port %></td>
        <td><%= link_to 'Edit', edit_dev_port_path(dev_port) %></td>
        <td><%= link_to 'Destroy', dev_port, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dev port', new_dev_port_path %>

app/views/dev_ports/new.html.erb
<h1>New Dev Port</h1>

<%= render 'form' %>

<%= link_to 'Back', dev_ports_path %>

app/views/dev_ports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dev_port.name %>
</p>

<p>
  <strong>Portno:</strong>
  <%= @dev_port.portno %>
</p>

<p>
  <strong>Type:</strong>
  <%= @dev_port.type %>
</p>

<p>
  <strong>Rackid:</strong>
  <%= @dev_port.RackID %>
</p>

<p>
  <strong>Odfid:</strong>
  <%= @dev_port.odfid %>
</p>

<p>
  <strong>Fiberid:</strong>
  <%= @dev_port.fiberid %>
</p>

<%= link_to 'Edit', edit_dev_port_path(@dev_port) %> |
<%= link_to 'Back', dev_ports_path %>