config/routes.rb
Rails.application.routes.draw do
  resources :cables
  resources :fiber_strands
  resources :dev_ports
  resources :term_devs
  resources :net_racks
  resources :locations

  root 'welcome#index'

end

app/models/fiber_strand.rb
class FiberStrand < ActiveRecord::Base
end

app/controllers/fiber_strands_controller.rb
class FiberStrandsController < ApplicationController
  before_action :set_fiber_strand, only: [:show, :edit, :update, :destroy]

  # GET /fiber_strands
  # GET /fiber_strands.json
  def index
    @fiber_strands = FiberStrand.all
  end

  # GET /fiber_strands/1
  # GET /fiber_strands/1.json
  def show
  end

  # GET /fiber_strands/new
  def new
    @fiber_strand = FiberStrand.new
  end

  # GET /fiber_strands/1/edit
  def edit
  end

  # POST /fiber_strands
  # POST /fiber_strands.json
  def create
    @fiber_strand = FiberStrand.new(fiber_strand_params)

    respond_to do |format|
      if @fiber_strand.save
        format.html { redirect_to @fiber_strand, notice: 'Fiber strand was successfully created.' }
        format.json { render :show, status: :created, location: @fiber_strand }
      else
        format.html { render :new }
        format.json { render json: @fiber_strand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fiber_strands/1
  # PATCH/PUT /fiber_strands/1.json
  def update
    respond_to do |format|
      if @fiber_strand.update(fiber_strand_params)
        format.html { redirect_to @fiber_strand, notice: 'Fiber strand was successfully updated.' }
        format.json { render :show, status: :ok, location: @fiber_strand }
      else
        format.html { render :edit }
        format.json { render json: @fiber_strand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fiber_strands/1
  # DELETE /fiber_strands/1.json
  def destroy
    @fiber_strand.destroy
    respond_to do |format|
      format.html { redirect_to fiber_strands_url, notice: 'Fiber strand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fiber_strand
      @fiber_strand = FiberStrand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fiber_strand_params
      params.require(:fiber_strand).permit(:name, :port1id, :port2id, :cableid)
    end
end

app/helpers/fiber_strands_helper.rb
module FiberStrandsHelper
end

app/views/fiber_strands/_form.html.erb
<%= form_for(@fiber_strand) do |f| %>
  <% if @fiber_strand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fiber_strand.errors.count, "error") %> prohibited this fiber_strand from being saved:</h2>

      <ul>
      <% @fiber_strand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :port1id %><br>
    <%= f.number_field :port1id %>
  </div>
  <div class="field">
    <%= f.label :port2id %><br>
    <%= f.number_field :port2id %>
  </div>
  <div class="field">
    <%= f.label :cableid %><br>
    <%= f.number_field :cableid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fiber_strands/edit.html.erb
<h1>Editing Fiber Strand</h1>

<%= render 'form' %>

<%= link_to 'Show', @fiber_strand %> |
<%= link_to 'Back', fiber_strands_path %>

app/views/fiber_strands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fiber Strands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Port1id</th>
      <th>Port2id</th>
      <th>Cableid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fiber_strands.each do |fiber_strand| %>
      <tr>
        <td><%= fiber_strand.name %></td>
        <td><%= fiber_strand.port1id %></td>
        <td><%= fiber_strand.port2id %></td>
        <td><%= fiber_strand.cableid %></td>
        <td><%= link_to 'Show', fiber_strand %></td>
        <td><%= link_to 'Edit', edit_fiber_strand_path(fiber_strand) %></td>
        <td><%= link_to 'Destroy', fiber_strand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fiber strand', new_fiber_strand_path %>

app/views/fiber_strands/new.html.erb
<h1>New Fiber Strand</h1>

<%= render 'form' %>

<%= link_to 'Back', fiber_strands_path %>

app/views/fiber_strands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fiber_strand.name %>
</p>

<p>
  <strong>Port1id:</strong>
  <%= @fiber_strand.port1id %>
</p>

<p>
  <strong>Port2id:</strong>
  <%= @fiber_strand.port2id %>
</p>

<p>
  <strong>Cableid:</strong>
  <%= @fiber_strand.cableid %>
</p>

<%= link_to 'Edit', edit_fiber_strand_path(@fiber_strand) %> |
<%= link_to 'Back', fiber_strands_path %>