config/routes.rb
Rails.application.routes.draw do
  resources :cables
  resources :fiber_strands
  resources :dev_ports
  resources :term_devs
  resources :net_racks
  resources :locations

  root 'welcome#index'

end

app/models/net_rack.rb
class NetRack < ActiveRecord::Base
    belongs_to :location
end

app/controllers/net_racks_controller.rb
class NetRacksController < ApplicationController
  before_action :set_net_rack, only: [:show, :edit, :update, :destroy]

  # GET /net_racks
  # GET /net_racks.json
  def index
    @net_racks = NetRack.all
  end

  # GET /net_racks/1
  # GET /net_racks/1.json
  def show
  end

  # GET /net_racks/new
  def new
    @net_rack = NetRack.new
    @locations = Location.all
  end

  # GET /net_racks/1/edit
  def edit
  end

  # POST /net_racks
  # POST /net_racks.json
  def create
    @net_rack = NetRack.new(net_rack_params)

    respond_to do |format|
      if @net_rack.save
        format.html { redirect_to @net_rack, notice: 'Net rack was successfully created.' }
        format.json { render :show, status: :created, location: @net_rack }
      else
        format.html { render :new }
        format.json { render json: @net_rack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /net_racks/1
  # PATCH/PUT /net_racks/1.json
  def update
    respond_to do |format|
      if @net_rack.update(net_rack_params)
        format.html { redirect_to @net_rack, notice: 'Net rack was successfully updated.' }
        format.json { render :show, status: :ok, location: @net_rack }
      else
        format.html { render :edit }
        format.json { render json: @net_rack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /net_racks/1
  # DELETE /net_racks/1.json
  def destroy
    @net_rack.destroy
    respond_to do |format|
      format.html { redirect_to net_racks_url, notice: 'Net rack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_net_rack
      @net_rack = NetRack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def net_rack_params
      params.require(:net_rack).permit(:name, :location_id)
    end
end

app/helpers/net_racks_helper.rb
module NetRacksHelper
end

app/views/net_racks/_form.html.erb
<%= form_for(@net_rack) do |f| %>
  <% if @net_rack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@net_rack.errors.count, "error") %> prohibited this net_rack from being saved:</h2>

      <ul>
      <% @net_rack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/net_racks/edit.html.erb
<h1>Editing Net Rack</h1>

<%= render 'form' %>

<%= link_to 'Show', @net_rack %> |
<%= link_to 'Back', net_racks_path %>

app/views/net_racks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Net Racks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @net_racks.each do |net_rack| %>
      <tr>
        <td><%= net_rack.name %></td>
        <td><%= net_rack.location_id %></td>
        <td><%= link_to 'Show', net_rack %></td>
        <td><%= link_to 'Edit', edit_net_rack_path(net_rack) %></td>
        <td><%= link_to 'Destroy', net_rack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Net rack', new_net_rack_path %>

app/views/net_racks/new.html.erb
<h1>New Net Rack</h1>


<%= render 'form' %>

<%= link_to 'Back', net_racks_path %>

app/views/net_racks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @net_rack.name %>
</p>

<p>
  <strong>Locationid:</strong>
  <%= @net_rack.locations_id %>
</p>

<%= link_to 'Edit', edit_net_rack_path(@net_rack) %> |
<%= link_to 'Back', net_racks_path %>